/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_push_browser_extension_chrome_testClipboard */

#ifndef _Included_com_push_lazyir_modules_clipboard_ClipboardJni
#define _Included_com_push_lazyir_modules_clipboard_ClipboardJni
#ifdef __cplusplus
extern "C" {
#endif

static bool worka;
/*
 * Class:     com_push_browser_extension_chrome_testClipboard
 * Method:    startListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_push_lazyir_modules_clipboard_ClipboardJni_startListener(JNIEnv *, jclass);


/*
 * Class:     com_push_browser_extension_chrome_testClipboard
 * Method:    stopListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_push_lazyir_modules_clipboard_ClipboardJni_stopListener (JNIEnv *, jclass);

/*
 * Class:     com_push_browser_extension_chrome_testClipboard
 * Method:    getClipboardText
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_push_lazyir_modules_clipboard_ClipboardJni_getClipboardText
  (JNIEnv *, jclass);

/*
 * Class:     com_push_browser_extension_chrome_testClipboard
 * Method:    setClipboardText
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_push_lazyir_modules_clipboard_ClipboardJni_setClipboardText
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif

