/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_push_browser_extension_chrome_testClipboard */

#ifndef _Included_com_push_browser_extension_chrome_testClipboard
#define _Included_com_push_browser_extension_chrome_testClipboard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_push_browser_extension_chrome_testClipboard
 * Method:    startListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_push_browser_extension_chrome_testClipboard_startListener
  (JNIEnv *, jclass);

/*
 * Class:     com_push_browser_extension_chrome_testClipboard
 * Method:    stopListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_push_browser_extension_chrome_testClipboard_stopListener
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
