#ifndef SERVERCLIPBOARD_GLOBAL_H
#define SERVERCLIPBOARD_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SERVERCLIPBOARD_LIBRARY)
#  define SERVERCLIPBOARDSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SERVERCLIPBOARDSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SERVERCLIPBOARD_GLOBAL_H
