/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_push_lazyir_modules_screenShare_ScreenShotJNi */

#ifndef _Included_com_push_lazyir_modules_screenShare_ScreenShotJNi
#define _Included_com_push_lazyir_modules_screenShare_ScreenShotJNi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_push_lazyir_modules_screenShare_ScreenShotJNi
 * Method:    getScreenShot
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_push_lazyir_modules_screenShare_ScreenShotJNi_getScreenShot
  (JNIEnv *, jobject);

/*
 * Class:     com_push_lazyir_modules_screenShare_ScreenShotJNi
 * Method:    getSizeX
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_push_lazyir_modules_screenShare_ScreenShotJNi_getSizeX
  (JNIEnv *, jobject);

/*
 * Class:     com_push_lazyir_modules_screenShare_ScreenShotJNi
 * Method:    getSizeY
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_push_lazyir_modules_screenShare_ScreenShotJNi_getSizeY
  (JNIEnv *, jobject);

/*
 * Class:     com_push_lazyir_modules_screenShare_ScreenShotJNi
 * Method:    startListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_push_lazyir_modules_screenShare_ScreenShotJNi_startListener
  (JNIEnv *, jobject);

/*
 * Class:     com_push_lazyir_modules_screenShare_ScreenShotJNi
 * Method:    stopListener
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_push_lazyir_modules_screenShare_ScreenShotJNi_stopListener
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif

