#ifndef SCREENSHAREJNI_GLOBAL_H
#define SCREENSHAREJNI_GLOBAL_H

#include <QtCore/qglobal.h>
#if defined(SCREENSHAREJNI_LIBRARY)
#  define SCREENSHAREJNISHARED_EXPORT Q_DECL_EXPORT
#else
#  define SCREENSHAREJNISHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SCREENSHAREJNI_GLOBAL_H
